{% set name = "amzn_pecos" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/amzn/pecos.git

build:
  number: 0
  script: |
    python -m pip install . -vv

requirements:
  build:
    - make
    - cmake
    - python={{ python }}
    - gxx={{ gxx }}
    - numpy>=1.19.5
    - blas
    - sphinx_rtd_theme
    - pytest-runner
    - scipy
    - scikit-learn
    - pytorch
    - click
    - transformers
    - sentencepiece
    - libgomp
  run:
    - python={{ python }}
    - libstdcxx-ng
    - numpy>=1.19.5
    - blas
    - sphinx_rtd_theme
    - scipy
    - scikit-learn
    - pytorch
    - click
    - transformers
    - sentencepiece

test:
  imports:
    - pecos.xmc
    - pecos.xmc.xlinear.model
  source_files:
    - test/tst-data/xmc/xlinear/

about:
  home: https://github.com/amzn/pecos
  license: Apache License 2.0
  license_family: APACHE
  summary: 'PECOS - Predictions for Enormous and Correlated Output Spaces'

extra:
  recipe-maintainers:
    - arita37
