{% set name = "hnsw2" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/arita37/cat_hnswlib/tree/master/python_bindings

build:
  number: 0
  script: |
    python -m pip install . -vv

requirements:
  build:
    - make
    - cmake
    - python={{ python }}
    - gxx={{ gxx }}
    - numpy>=1.19.5
    - blas
    - sphinx_rtd_theme
    - pytest-runner
    - scipy
    - scikit-learn
    - pytorch
    - click
    - transformers
    - sentencepiece
    - libgomp
  run:
    - python={{ python }}
    - libstdcxx-ng
    - numpy>=1.19.5
    - blas
    - sphinx_rtd_theme
    - scipy
    - scikit-learn
    - pytorch
    - click
    - transformers
    - sentencepiece

test:
  imports:
    - import hnswlib
  source_files:
    - python_bindings/tests/

about:
  home: hnsw2
  license: Apache License 2.0
  license_family: APACHE
  summary: 'hnsw2'

extra:
  recipe-maintainers:
    - arita37
